### ISSUE TITLE
Design incomplet, fereastra cu întrebari are probleme și nu este disponibil puzzle-ul

### ISSUE THREAD

**Issue by TeaBoomer29** [RunaAM/crossword#1]
Buna! Aplicatia este foarte buna,m-am distrat incercand sa ghicesc cuvintele din rebus, mai ales ca zilele astea trebuie sa fiu ascultat din opera Ion si am cateva dificultati in a tine minte numele tuturor personajelor, diverse evenimente din poveste s.a.m.d.. Singurele probleme care m-au nesatisfacut sunt: bara cu clues dispare atunci cand o bag in bara si navighez pe altceva. Design-ul nu e prea placut, mai ales ordinea patratelor. As fi preferat o ordine putin mai complexa, in care pe mijloc sau orice pozitie sa iasa numele operei sau chiar numele autorului. O alta problema am observat la cuvantul Ion. Aplicatia pare sa imi arate ca I-ul din Ion este gresit si nu pot intelege de ce. Pe viitor sper sa se adauge intrebari mai grele legate de opera, pentru a retine totul mai usor si pentru a-i ajuta pe elevii ca mine. Mult noroc! 8.50/10

**Comment by viktorunix** [comment]
Progres pentru rezolvare:

- [x] fixare fereastra cu intrebari
- [x] schimbarea interfata UI
- [ ] creare puzzle
